---
- name: gather os specific variables
  include_vars:
    file: "{{ pycharm_version }}/{{ ansible_distribution }}.yml"

- name: customize /etc/hosts
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ interpreters.inasafe_realtime.domain_alias }}$'
    line: '{{ interpreters.inasafe_realtime.ipaddress }} {{ interpreters.inasafe_realtime.domain_alias }}'
    state: present

- name: customize project configuration
  template:
    src: docker-realtime-orchestration.iml
    dest: '{{ project_path }}/.idea/docker-realtime-orchestration.iml'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"

- name: customize remote-mappings configurations
  template:
    src: remote-mappings.xml
    dest: '{{ project_path }}/.idea/remote-mappings.xml'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"

- name: customize vcs configurations
  template:
    src: vcs.xml
    dest: '{{ project_path }}/.idea/vcs.xml'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"

- name: customize dockerized python interpreter
  template:
    src: 'python-interpreter/{{ item }}'
    dest: '{{ project_path }}/ansible/tmp/{{ item }}'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
  with_items:
    - inasafe-realtime.xml.j2
    - inasafe-shakemap-monitor.xml.j2
    - inasafe-shakemap-monitor-bnpb.xml.j2
    - inasafe-shakemap-corrected-monitor.xml.j2

- name: inject python interpreter definitions
  command: python inject_python_interpreter.py "{{ pycharm_settings_path }}/options/jdk.table.xml" "{{ project_path }}/ansible/tmp/{{ item }}"
  with_items:
    - inasafe-realtime.xml.j2
    - inasafe-shakemap-monitor.xml.j2
    - inasafe-shakemap-monitor-bnpb.xml.j2
    - inasafe-shakemap-corrected-monitor.xml.j2
  args:
    chdir: "{{ project_path }}/ansible/development/roles/pycharm/files/"

- name: customize run/debug configurations
  template:
    src: workspace-configuration.xml.j2
    dest: '{{ project_path }}/ansible/tmp/workspace-configuration.xml'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"

- name: inject run/debug configurations
  command: python inject_run_configurations.py "{{ project_path }}/.idea/workspace.xml" "{{ project_path }}/ansible/tmp/workspace-configuration.xml"
  args:
    chdir: "{{ project_path }}/ansible/development/roles/pycharm/files/"
